### ISSUE TITLE
Support for parallel builds

### ISSUE THREAD

**Issue by itsmeduncan** [jobready/codeclimate-test-reporter-buildkite-plugin#2]
Hi there,

This plugin is great, and works well with a single build. Is there any plan to support the stitching together parallel builds' test coverage?

Thanks for open sourcing this!

**Comment by s01ipsist** [comment]
We aren't in need of that immediately but agree it would be a great addition. Happy to help review a PR.
We really just need to add a step for https://github.com/codeclimate/test-reporter/blob/master/man/cc-test-reporter-sum-coverage.1.md . If it will accept a wild card, we could possibly have the same script support one or many artifacts.
